name: UVA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16285
title: ULTRA VIOLET ABSTRACTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#253b77'
    - '#609fbe'
    - '#71cbdd'
    - '#395a8c'
    - '#4f7da5'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
