name: Ultra Violet Abstracts
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16285
title: iridescent abstract UV paintings and experimental electronic music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#273270'
    - '#8acfde'
    - '#66a3c2'
    - '#3a4a80'
    - '#6886ab'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
